### ISSUE TITLE
Can you please upload this to maven?

### ISSUE THREAD

**Issue by ticofab** [darsh2/MultipleImageSelect#1]
It's much better to have it as a gradle dependency. Thanks!

**Comment by darsh2** [comment]
@ticofab I plan on adding video picker functionality as well, thought of uploading it to maven after that. But yeah, you're right. If this takes long, I'll upload it soon.

**Comment by jitpack-io** [comment]
Hi!
Perhaps this will be useful in the meantime. It's available as a Gradle dependency from:
https://jitpack.io/#darsh2/MultipleImageSelect/9aa3325c0b

Would be also nice to have a GitHub release.

**Comment by darsh2** [comment]
@jitpack-io Thank you for making this project to be available as a Gradle dependency! I was busy the past couple of weeks and hence couldn't work on this.

**Comment by jitpack-io** [comment]
@darsh2 You're welcome! That's what we do:)

**Comment by darsh2** [comment]
Added gradle dependency and github release. Closing this issue.
