### ISSUE TITLE
Can not move back-and-forth in image picker

### ISSUE THREAD

**Issue by harshvishu** [darsh2/MultipleImageSelect#3]
There is no back button on the actionBar.
If by mistake i have selected a wrong album i have to go back entirely and open the image picker again.
Is there any way to avoid this.

**Comment by darsh2** [comment]
At present, no. You have to open image picker again. I'm a bit busy now, will work on this soon

**Comment by darsh2** [comment]
The new release (v0.0.2) fixes this issue. If you still face any problems, reopen this issue.
