### ISSUE TITLE
Image adding limitation toast message not working

### ISSUE THREAD

**Issue by nimitsolanki** [darsh2/MultipleImageSelect#6]
Hi, If user select more then configured images, then after pressing "ADD" button, "Can select maximum of 0 images" toast displaying. Instead of that, It should display configured number.

**Comment by darsh2** [comment]
Thanks. Fixed this in latest commit.

**Comment by nimitsolanki** [comment]
@darsh2 version name ?

**Comment by darsh2** [comment]
Just created a new release, use v0.0.3

**Comment by nimitsolanki** [comment]
thanks @darsh2
