### ISSUE TITLE
Theme should be editable 

### ISSUE THREAD

**Issue by nimitsolanki** [darsh2/MultipleImageSelect#7]
Hi @darsh2 , 

I want to use default app theme, What should I do ? Check MultipleImageSelectTheme style.

**Comment by darsh2** [comment]
In your AndroidManifest.xml under the app node, remove the line android:theme="@style/MultipleImageSelectTheme" , and replace it with a custom theme. This should work I guess.

**Comment by Bluesir9** [comment]
yeah by adding tools:replace="android:theme" and your own theme as mentioned above, it works. But the same does not reflect in the ImageSelectActivity. Also the action bar label disappears when I do that.

**Comment by darsh2** [comment]
Hey, my apologies for the really late fix. You can read here about using custom themes https://github.com/darsh2/MultipleImageSelect/blob/master/README.md#custom-styles

**Comment by darsh2** [comment]
Closing this issue as for now as commit c40f586 solves this.
