### ISSUE TITLE
Permission denial error 

### ISSUE THREAD

**Issue by jeetdholakia** [darsh2/MultipleImageSelect#9]
Hey guys,

Im getting this error ... Ive tried setting android:exported = true in my manifest as well, but it doesn't work. And I've also provided the read/write permissions.

10-05 12:15:21.611 28063-28171/com.sand5.giflab E/AndroidRuntime: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=28063, uid=10151 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()

Please help me out...
Thanks

**Comment by darsh2** [comment]
Hello,

The permission to read external storage is added in this library's manifest file. I'm not certain what could be causing the error. In any case android:exported=true is not required as this is not a service. Can you post a snapshot of your manifest file?

**Comment by darsh2** [comment]
Latest commit should fix this issue as it now supports run time permissions
